---
title: "winter_datathon_26"
author: "Fiona, Nicolle, Kevin"
date: "2026-02-20"
output: pdf_document
---
#list of cleaned columns
#IMDB rating, Run Time, 

# cleaning dataset

```{r}
library(tidyverse)

x <- c(1)
movies_data <- read.csv("movie_data.csv")
attach(movies_data)
movies_clean <- movies_data
movies_clean %>% map(~sum(is.na(.)))

movies_data <- read.csv("movie_data.csv")
head(movies_data)

movies_data <- drop_na(movies_data)
movies_clean <- movies_data
movies_clean %>% map(~sum(is.na(.)))

movies_clean$Run.Time <- movies_data$Run.Time %>% str_extract_all("\\d+") %>% map(~as.numeric(.)) %>%
  map(~.[1] * 60 + .[2]) %>% unlist()
```

```{r runtime cleanup}
movies_clean$Run.Time <- movies_data$Run.Time %>% str_extract_all("\\d+") %>% map(~as.numeric(.)) %>%
  map(~.[1] * 60 + .[2]) %>% unlist()
```

```{r imdb review cleanup}
km <- function(string){
  if(!is.na(as.numeric(string))){
    num <- as.numeric(string)
  }
  if(str_detect(string, "K")){
    num <- as.numeric(str_sub(string, 1, -2)) * 1000
  }
  if(str_detect(string, "M")){
    num <- as.numeric(str_sub(string, 1, -2)) * 1000000
  }
  num
}

movies_clean$Count.of.IMDb.Ratings <- movies_data$Count.of.IMDb.Ratings %>% 
  map_dbl(~km(.)) 
```

```{r genre cleanup}
movies_wide_genres <- movies_data %>% select(Title, Genre) %>% 
  separate_rows(Genre, sep = ",") %>%
  mutate(present = TRUE) %>%
  pivot_wider(
    names_from = Genre,
    values_from = present,
    values_fill = FALSE,
    values_fn = any
  )

movies_clean <- movies_clean %>% inner_join(movies_wide_genres, by = "Title")
```

```{r release date}
library(dplyr)
library(tidyr)

movies_data |> 
  separate(
    Release.Date,
    into = c("date", "country"),
    sep = "\\(", 
    fill= "right"
    ) |>
        mutate(date = str_trim(date),
                country = str_trim(sub("\\)$", "", country)),
                month = str_extract(date, "^[A-Za-z]+")
              ) |>
                relocate(month, .before = date)
```

```{r budget}
library(tidyverse)
library(readr)
library(stringr)

#assume 3% average annual inflation
base_year <- 2026
annual_inflation <- 0.03 

#identify what currencies are there
movies_data %>%
  mutate(budget_currency = str_trim(str_extract(Budget, "^[^0-9]+"))) %>%
  count(budget_currency, sort = TRUE)

#exchange rates as of 20 Feb 2026
exchange_rates <- tibble(
  budget_currency = c("$", "£", "EUR", "CA$", "A$", "¥", "RUR", "₹", "CN¥", "R$", "THB"),
  rate_to_usd = c(
    1.00,   # USD
    1.35,   # GBP
    1.18,   # EUR
    0.73,   # CAD
    0.71,   # AUD
    0.0065, # JPY
    0.013,  # RUR (old russian ruble)
    0.011,  # INR
    0.14,   # CNY
    0.19,   # BRL
    0.032   # THB
  )
)

#convert
movies_clean <- movies_data %>%
  mutate(
    budget_usd_2026 = {
      currency <- str_trim(str_extract(Budget, "^[^0-9]+"))
      currency[is.na(currency)] <- "$"

      # standardize: old currencies to euro
      currency[currency == "€"] <- "EUR"
      currency[currency %in% c("DEM", "FRF")] <- "EUR"

      value <- parse_number(Budget) 

      rate <- exchange_rates$rate_to_usd[match(currency, exchange_rates$budget_currency)]
      rate[is.na(rate)] <- 1  # if no currency, treat as USD

      years <- base_year - as.integer(Year) 

      (value * rate) * (1 + annual_inflation)^years #inflate to 2026 USD (future value formula)
    }
  )
```

```{r domestic gross}
class(movies_clean[["Domestic.Gross"]][1]) #so we know its a character

movies_clean[["Domestic.Gross"]] <- as.numeric(gsub("[\\$,]", "", movies_clean[["Domestic.Gross"]]))

class(movies_clean[["Domestic.Gross"]][1])

#apply for other 2 gross figs
```

```{r domestic weekend gross}
movies_clean[["Domestic.Weekend.Gross"]] <- as.numeric(gsub("[\\$,]", "", movies_clean[["Domestic.Weekend.Gross"]]))
```

```{r worldwide gross}
movies_clean[["Worldwide.Gross"]] <- as.numeric(gsub("[\\$,]", "", movies_clean[["Worldwide.Gross"]]))
```

```{r ratings cleanup}
movies_clean[["Rotten.Tomatoes.Rating"]] <- as.numeric(gsub("%", "", movies_clean[["Rotten.Tomatoes.Rating"]]))
```


```{r gross account for inflation}
library(dplyr)
library(readr)

movies_clean <- movies_clean %>%
  mutate(
    domestic_gross_2026 =
      Domestic.Gross *
      (1 + annual_inflation)^(base_year - as.integer(Year)),

    domestic_weekend_gross_2026 =
      Domestic.Weekend.Gross *
      (1 + annual_inflation)^(base_year - as.integer(Year)),

    worldwide_gross_2026 =
      Worldwide.Gross *
      (1 + annual_inflation)^(base_year - as.integer(Year))
  )
```

```{r}
#clean plot
movies_clean <- movies_clean %>%
  mutate(
    Plot = str_replace_all(Plot, "&apos;", "'"),
    Plot = str_replace_all(Plot, "&quot;", "\""),
    Plot = str_replace_all(Plot, "&amp;", "&")
  )
```

```{r}
#install.packages("tidytext")
#install.packages("textdata")
library(tidytext)
library(textdata)
library(dplyr)
library(stringr)

plot_words <- movies_clean %>%
  select(Title, Plot) %>%
  mutate(Plot = tolower(Plot)) %>%
  unnest_tokens(word, Plot)

afinn <- get_sentiments("afinn")

plot_sentiment <- plot_words %>%
  inner_join(afinn, by = "word") %>%
  group_by(Title) %>%
  summarise(
    plot_sentiment = mean(value),
    sentiment_sum = sum(value),
    word_count = n()
  )

movies_clean <- movies_clean %>%
  left_join(plot_sentiment, by = "Title")


```

```{r}
library(tidytext)
library(dplyr)

plot_words <- movies_clean %>%
  unnest_tokens(word, Plot)

plot_words %>%
  count(word, sort = TRUE) %>%
  filter(!word %in% stop_words$word) %>%
  slice_max(n, n = 100)
```

```{r}
model <- lm(worldwide_gross_2026 ~ 
     plot_sentiment +
     budget_usd_2026 +
     IMDb.Rating,
   data = movies_clean)

summary(model)
```

```{r}
#runtime effect on ratings 

#rotten tomato ratings
attach(movies_clean)
runtime_vs_rating_rt <- lm(Rotten.Tomatoes.Rating ~ Run.Time)
summary(runtime_vs_rating_rt)
plot(runtime_vs_rating_rt)

#IMdb ratings
imdb_ratings_proportion <- IMDb.Rating * Count.of.IMDb.Ratings
runtime_vs_rating_imdb <- lm(imdb_ratings_proportion ~ Run.Time)
summary(runtime_vs_rating_imdb)
plot(runtime_vs_rating_imdb)

#metascore ratings
runtime_vs_rating_meta <- lm(Metascore.Rating ~ Run.Time)
summary(runtime_vs_rating_meta)
plot(runtime_vs_rating_meta)

```

